### ISSUE TITLE
[macro issue] implemetation roadmap

### ISSUE THREAD

**Issue by zhenfeizhang** [scroll-tech/ceno#8]
# pre 2/2; end to end demo, part 1

- [ ] zkVM
   - [x] opcode design (week 2/3, Tianyi) #37
   - [x] API design #37
   - [ ] Generate wires in with interpreter (week 4, Yuncong)
   - [x] Use gkr graph API to construct chips (week 4, Tianyi) #37
     - [x] Refactor on the branch [singer-dev5](https://github.com/scroll-tech/singer/tree/singer-dev5) based on simple-frontend.
   - [ ] #40
   - [ ] example (circuit + prover + verifier)
   - [ ] recursive verifier
- [ ] gkr circuit graph
   - [x] API design #23 (week 1/2, ready for review, Wenqing)
   - [x] simple Implementation #35 
- [x] Front end ~#4~ #15 
- [ ] Back end
  - [x] Goldilocks
    - [x] extension field #9 (week 1)
    - [x] #28
    - [x] https://github.com/zhenfeizhang/Goldilocks/issues/2
  - [x] sum check 
    - [x] extension field #10 (week 1)
  - [x] GKR #13 #16 (review and merge, week 1)
    - [x] #29
    - [x] GKR with PCS examples (week 3, Yungcong)
  - [ ] pcs
    - [x] API #5 
    - [x] BaseFold [code](https://github.com/scroll-tech/plonkish_basefold/blob/main/plonkish/plonkish_backend/src/pcs/multilinear/basefold.rs) (evaluate, week 1)
    - [x] batching over base field(week 2, yuncong) https://github.com/scroll-tech/singer/pull/18
    - [x] field -> Goldilocks ext
      - [x] allow polynomial to be over both base and extension field? (week 2, yuncong, ready for review ZZ)
    - [ ] integrate PCS into our library (week 5 yuncong); unit tests OK, pending integration
